config/routes.rb
Rails.application.routes.draw do
  root 'people#index'

  get '/about', to: 'static_people#about'

  resources :people
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
class Person < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    @people = Person.all
  end

  def show
    @person = Person.find(params[:id])
  end

  def new
    @person = Person.new
  end

  def create
    @person = Person.new(people_params)

    if @person.save
      redirect_to people_path
    else
      render :new
    end
  end

  def edit
    @person = Person.find(params[:id])
  end

  def update
    @person = Person.find(params[:id])

    if @person.update(person_params)
      redirect_to people_path
    else
      render :edit
    end
  end

  private

    def people_params
      params.require(:person).permit(:first_name, :last_name, :age, :hair_color, :eye_color, :gender)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/_navbar.html.erb
<%= link_to 'Home', root_path %>
<%# link_to 'About', about_path %>
<%= link_to 'Pages', people_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PersonList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%# javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/people/edit.html.erb
<h1>Edit Person</h1>
<%= form_for @person do |f| %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>

  <%= f.label :last_name %>
  <%= f.text_field :last_name %>

  <%= f.label :age %>
  <%= f.text_field :age %>

  <%= f.label :hair_color %>
  <%= f.text_field :hair_color %>

  <%= f.label :eye_color %>
  <%= f.text_field :eye_color %>

  <%= f.label :gender %>
  <%= f.text_field :gender %>

  <%= f.submit %>
<% end %>

app/views/people/index.html.erb
<h1>People</h1>
<p><%= link_to 'New Person', new_person_path %></p>
<% @people.each do |person| %>
  <h2><%= person.first_name %></h2>
  <%= link_to 'Show Page', person_path(person) %>
<%= link_to 'Edit Person', edit_person_path(person) %>
  <% end %>
  

app/views/people/new.html.erb
<h1>New Person</h1>
<%= form_for @person do |f| %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>

  <%= f.label :last_name %>
  <%= f.text_field :last_name %>

  <%= f.label :age %>
  <%= f.text_field :age %>

  <%= f.label :hair_color %>
  <%= f.text_field :hair_color %>

  <%= f.label :eye_color %>
  <%= f.text_field :eye_color %>

  <%= f.label :gender %>
  <%= f.text_field :gender %>

  <%= f.submit %>
<% end %>

app/views/people/show.html.erb
<h1><%= @person.first_name %></h1>
<h1><%= @person.last_name %></h1>
<h4><%= @person.age %></h4>
<h4><%= @person.hair_color %></h4>
<h4><%= @person.eye_color %></h4>
<h4><%= @person.gender %></h4>
<%= link_to 'Back', people_path %>